In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
lst=[3,6,5,4]
arr=np.array(lst)
arr

array([3, 6, 5, 4])

In [34]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Sequence

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)  #start, stop(exclusive), interval

array([ 0,  2,  4,  6,  8, 10])

### Special Arrays 

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.linspace(0.5,10,20) #start, stop(inclusive), total number you want in that interval

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

### Identity Matrix 

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array of Random Numbers 

In [13]:
np.random.rand(5) #array of random numbers between 0,1

array([0.43764145, 0.02555014, 0.33140508, 0.22082058, 0.74961222])

In [14]:
np.random.rand(3,3) 

array([[0.45580278, 0.13024638, 0.88101358],
       [0.076894  , 0.49239599, 0.18170395],
       [0.97465562, 0.95302025, 0.96431469]])

In [15]:
np.random.randn(4) #returns sample form standard normal

array([-0.80797429,  0.58737496, -0.67739529, -0.72824774])

In [16]:
np.random.randn(3,3)

array([[-1.17376075,  0.94228415, -0.65272318],
       [ 0.35339114,  1.41944361, -0.28186815],
       [-1.93535946, -0.77171086, -0.50748551]])

In [17]:
np.random.randint(0,68)  #low= inclusive, high= exclusive

51

In [18]:
np.random.randint(1,100,10)

array([64, 57, 19, 74, 68, 11, 11, 56, 79, 60])

In [19]:
arr=np.arange(20)

In [37]:
array=arr.reshape(5,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
ranarr=np.random.randint(0,10,10)

In [22]:
ranarr

array([5, 3, 0, 0, 5, 1, 3, 7, 7, 1])

In [23]:
ranarr.max()

7

In [24]:
ranarr.min()

0

In [25]:
ranarr.mean()

3.2

In [26]:
ranarr.std()

2.5612496949731396

In [27]:
ranarr.argmin()

2

In [28]:
ranarr.argmax()

7

In [30]:
arr.shape

(20,)

In [31]:
ranarr.shape

(10,)

In [38]:
array.shape

(5, 4)

In [39]:
ranarr.dtype

dtype('int32')

In [1]:
from numpy.random import randint

In [2]:
randint(0,10)

3

In [7]:
arr=randint(0,10,4)
arr

array([4, 8, 4, 8])

In [9]:
arr.reshape(2,2)

array([[4, 8],
       [4, 8]])