In [1]:
import numpy as np

In [2]:
from numpy.random import randint

In [3]:
arr=randint(0,11,10)

In [4]:
arr

array([ 1,  8,  3,  5,  8,  6,  9,  9, 10, 10])

In [5]:
arr[8]

10

In [6]:
arr[1:5]

array([8, 3, 5, 8])

In [7]:
arr[:]

array([ 1,  8,  3,  5,  8,  6,  9,  9, 10, 10])

In [8]:
arr[5:]

array([ 6,  9,  9, 10, 10])

In [9]:
arr[:6]

array([1, 8, 3, 5, 8, 6])

In [11]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   6,   9,   9,  10,  10])

In [16]:
#numpy changes the whole array. To avoid this

In [21]:
arr=randint(0,11,10)
arr

array([10,  7,  7,  3,  9,  4,  2,  8,  5,  3])

In [22]:
arr_copy=arr.copy()
arr

array([10,  7,  7,  3,  9,  4,  2,  8,  5,  3])

In [24]:
arr_copy[0:5]=100
arr_copy

array([100, 100, 100, 100, 100,   4,   2,   8,   5,   3])

In [25]:
arr

array([10,  7,  7,  3,  9,  4,  2,  8,  5,  3])

### 2d Array 

In [32]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[1][1]

25

In [34]:
arr_2d[1,1]

25

In [35]:
arr_2d[:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
arr_2d[1:,]

array([[20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [41]:
arr_2d[1:,:1]

array([[20],
       [35]])

In [43]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [45]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [47]:
arr=randint(0,11,10)
arr

array([ 5,  6,  4,  4,  9,  9,  9,  8,  3, 10])

In [48]:
arr[arr>5]

array([ 6,  9,  9,  9,  8, 10])

In [64]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [65]:
arr_2d[2:4,1:5]

array([[21, 22, 23, 24],
       [31, 32, 33, 34]])