In [1]:
import numpy as np

In [7]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
arr+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [13]:
arr-100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

In [14]:
arr*100

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [16]:
arr/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [17]:
arr**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

### Universal Array Operations 

In [18]:
np.mean(arr)

5.5

In [19]:
arr.mean()

5.5

In [20]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [22]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [23]:
np.max(arr)

10

In [25]:
np.min(arr)

1

In [26]:
np.std(arr)

2.8722813232690143

In [27]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [28]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [29]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [30]:
np.log(arr) #base 'e'

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])